name: CI matrix (5.x)
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
jobs:
  CI-5_x-Java_11:
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      jdk: 11
    secrets: inherit
  CI-5_x-Java_17:
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      jdk: 17
    secrets: inherit
